### ISSUE TITLE
VIVO-228: SimpleChangeRecord should attempt to create the changedData directory.

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#1920]
[Brian Caruso](https://github.com/bdc34) (Migrated from [VIVO-228](https://vivo-project.atlassian.net/browse/VIVO-228)) said:

I think that we have seen this issue before but it would be great if this could would attempt to create the directory that it needs before giving up. 

2013-07-31 09:33:37,982 WARN  [UpdateKnowledgeBase] warning                                                     
java.lang.RuntimeException: edu.cornell.mannlib.vitro.webapp.ontology.update.SimpleChangeRecord unable to creat\
e required file at /usr/local/tomcat/webapps/vivo/WEB-INF/ontologies/update/changedData/addedData.n3            
    at edu.cornell.mannlib.vitro.webapp.ontology.update.SimpleChangeRecord.<init>(SimpleChangeRecord.java:35)   
    at edu.cornell.mannlib.vitro.webapp.ontology.update.KnowledgeBaseUpdater.<init>(KnowledgeBaseUpdater.java:5\
8)                                                                                                              
    at edu.cornell.mannlib.vitro.webapp.servlet.setup.UpdateKnowledgeBase.contextInitialized(UpdateKnowledgeBas\
e.java:144)                                                                                                     
    at edu.cornell.mannlib.vitro.webapp.startup.StartupManager.initialize(StartupManager.java:176)              
    at edu.cornell.mannlib.vitro.webapp.startup.StartupManager.contextInitialized(StartupManager.java:65)       
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4206)                        
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4705)

**Comment by chenejac** [comment]
This issue is related to #1758
