### ISSUE TITLE
VIVO-231: Quiet "no edit configuration" error

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#1923]
[Brian Caruso](https://github.com/bdc34) (Migrated from [VIVO-231](https://vivo-project.atlassian.net/browse/VIVO-231)) said:

Change this from an ERROR to a WARN and get rid of the stack trace. Since this could be an attack print out IP address.

2013-07-30 14:26:24,432 ERROR [FreemarkerHttpServlet] java.lang.Error: No edit configuration found.                                                                                                                
java.lang.Error: No edit configuration found.                                                                                                                                                                      
    at edu.cornell.mannlib.vitro.webapp.edit.n3editing.controller.ProcessRdfFormController.processRequest(ProcessRdfFormController.java:65)                                                                        
    at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:102)                                                                                          
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)                                                                                                                                                
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)                                                                                                                                                
    at edu.cornell.mannlib.vitro.webapp.controller.VitroHttpServlet.service(VitroHttpServlet.java:63)                                                                                                              
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)                                                                                                           
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

**Comment by chenejac** [comment]
This issue is related to #1878
