### ISSUE TITLE
VIVO-1045: "Manage Jena Models" page should have safeguards

### ISSUE THREAD

**Issue by chenejac** [vivo-project/VIVO#2729]
[Jim Blake](https://github.com/j2blake) (Migrated from [VIVO-1045](https://vivo-project.atlassian.net/browse/VIVO-1045)) said:

The page at http://localhost:8080/vivo/ingest?action=listModels allows you to "clear statements" on any named graph in the triple store. It would help if the "clear statements" button lead to an "are you sure?" dialog, naming the model that was about to be cleared. In addition, it would be good if the completed operation produced a message on the page saying which model had been cleared. These steps would help an admin to avoid error, or at least to know which error had been committed.

**Comment by hauschke** [comment]
Upvote! This should really be the case! The message should say something like "Are you sure? Proceeding will delete all statements in this Jena Model. Make sure that you create a backup." or something similar.

**Comment by meyerfo** [comment]
It’s quite easy to delete Jena Models from the Ingest menu as well. This applies not only to models you’ve created yourself, but also to existing ones.
In my view, it would make sense to add a confirmation prompt to the ‘Remove’ button. I received the following error message when trying to delete one of the models. 
If you accidently delete the wrong Jena Model file, an error will appear when you open "Site Admin" page.

In theory, and probably in practice too, clicking on this page (Available Jena Models) by mistake could cause a serious error.

` There was an error in the system.

Error message: already closed

Stack trace (full trace available in the vivo log): org.apache.jena.shared.ClosedException: already closed at org.apache.jena.graph.impl.GraphBase.checkOpen(GraphBase.java:66) at org.apache.jena.graph.impl.GraphBase.find(GraphBase.java:243) at org.apache.jena.graph.compose.MultiUnion.multiGraphFind(MultiUnion.java:171) at org.apache.jena.graph.compose.MultiUnion.graphBaseFind(MultiUnion.java:148) at org.apache.jena.graph.impl.GraphBase.find(GraphBase.java:244) at org.apache.jena.graph.compose.Union._graphBaseFind(Union.java:65) at org.apache.jena.graph.compose.Dyadic.graphBaseFind(Dyadic.java:57) at org.apache.jena.graph.impl.GraphBase.find(GraphBase.java:244) at org.apache.jena.graph.compose.MultiUnion.singleGraphFind(MultiUnion.java:157) at org.apache.jena.graph.compose.MultiUnion.graphBaseFind(MultiUnion.java:148) at org.apache.jena.graph.impl.GraphBase.find(GraphBase.java:244) at org.apache.jena.graph.impl.GraphBase.graphBaseFind(GraphBase.java:261) at org.apache.jena.graph.impl.GraphBase.find(GraphBase.java:258) at org.apache.jena.rdf.model.impl.ModelCom.listStatements(ModelCom.java:498) at org.apache.jena.rdf.model.impl.ModelCom.listStatements(ModelCom.java:503) at edu.cornell.mannlib.vitro.webapp.rdfservice.adapters.AbstractOntModelDecorator.listStatements(AbstractOntModelDecorator.java:1014) at edu.cornell.mannlib.vitro.webapp.dao.jena.VClassDaoSDB.addVClassesToGroup(VClassDaoSDB.java:58) at edu.cornell.mannlib.vitro.webapp.dao.jena.VClassGroupDaoJena.getPublicGroupsWithVClasses(VClassGroupDaoJena.java:149) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.BaseSiteAdminController.getDataInputData(BaseSiteAdminController.java:150) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.BaseSiteAdminController.processRequest(BaseSiteAdminController.java:104) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:109) at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) at edu.cornell.mannlib.vitro.webapp.controller.VitroHttpServlet.service(VitroHttpServlet.java:69) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at org.apache.catalina.filters.ExpiresFilter.doFilter(ExpiresFilter.java:1227) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doNonDisplayPage(PageRoutingFilter.java:112) at edu.cornell.mannlib.vitro.webapp.filters.PageRoutingFilter.doFilter(PageRoutingFilter.java:103) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.ClickjackFilter.doFilter(ClickjackFilter.java:34) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.RequestModelsPrep.doFilter(RequestModelsPrep.java:59) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.URLRewriterFilter.doFilter(URLRewriterFilter.java:40) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.JSessionStripFilter.doFilter(JSessionStripFilter.java:63) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.produceBasicResponse(CachingResponseFilter.java:321) at edu.cornell.mannlib.vitro.webapp.filters.CachingResponseFilter.doFilter(CachingResponseFilter.java:120) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.i18n.selection.LocaleSelectionFilter.doFilter(LocaleSelectionFilter.java:64) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:36) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.SessionTimeoutLimitingFilter.doFilter(SessionTimeoutLimitingFilter.java:41) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at edu.cornell.mannlib.vitro.webapp.filters.StartupStatusDisplayFilter.doFilter(StartupStatusDisplayFilter.java:67) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:829) `
