### ISSUE TITLE
Error creating Inferences for academic articles

### ISSUE THREAD

**Issue by naveen1707** [vivo-project/VIVO#3602]
**Describe the bug**
During harvester process , new academic articles are added into VIVO and subsequently recompute process is initiated at the end which creates automatic inferences in the VIVO.

Academic article has subject area with below 
  <academic article URI> vivo:hasSubjectArea <subjectAreaURI>

Automatic inference to be generated for above one 
  <subjectAreaURI> vivo:subjectAreaOf  <academic article URI>

**To Reproduce**
1. Run any harvester process 
2. Initiate Recompute Inference process on the application manually or through bash script
3. Look into vivo.all.log for errors

**Expected behavior**
   Recompute inference should generate Triples with subjectAreaOf predicate.

**Environment (please complete the following information):**
 - OS: Linux
 - Browser : Chrome
 - Tomcat version : 8.5
 - VIVO version:  1.10
 - Apache Solr or ElasticSearch version

**Additional context**
Exception trace for this issue : 

2021-09-20 18:38:02,115 ERROR [ABoxRecomputer] Error recomputing inferences for individual <http://vivo.epa.gov/vivo/individual/academicarticle166174825>
org.apache.jena.sparql.JenaTransactionException: Already closed
	at org.apache.jena.tdb.transaction.DatasetGraphTransaction.checkNotClosed(DatasetGraphTransaction.java:140)
	at org.apache.jena.tdb.transaction.DatasetGraphTransaction.checkNotActive(DatasetGraphTransaction.java:133)
	at org.apache.jena.sparql.core.DatasetGraphTrackActive.begin(DatasetGraphTrackActive.java:39)
	at org.apache.jena.sparql.core.DatasetImpl.begin(DatasetImpl.java:111)
	at edu.cornell.mannlib.vitro.webapp.rdfservice.impl.jena.tdb.RDFServiceTDB.sparqlConstructQuery(RDFServiceTDB.java:117)
	at edu.cornell.mannlib.vitro.webapp.rdfservice.impl.RDFServiceFactorySingle$UnclosableRDFService.sparqlConstructQuery(RDFServiceFactorySingle.java:101)
	at edu.cornell.mannlib.vitro.webapp.rdfservice.impl.logging.LoggingRDFService.sparqlConstructQuery(LoggingRDFService.java:55)
	at edu.cornell.mannlib.vitro.webapp.reasoner.ABoxRecomputer.getAssertions(ABoxRecomputer.java:329)
	at edu.cornell.mannlib.vitro.webapp.reasoner.ABoxRecomputer.recomputeIndividual(ABoxRecomputer.java:233)
	at edu.cornell.mannlib.vitro.webapp.reasoner.ABoxRecomputer.recomputeIndividuals(ABoxRecomputer.java:186)
	at edu.cornell.mannlib.vitro.webapp.reasoner.ABoxRecomputer.recompute(ABoxRecomputer.java:130)
	at edu.cornell.mannlib.vitro.webapp.reasoner.SimpleReasoner.recompute(SimpleReasoner.java:1111)
	at edu.cornell.mannlib.vitro.webapp.controller.freemarker.SimpleReasonerRecomputeController$Recomputer.run(SimpleReasonerRecomputeController.java:101)
	at java.lang.Thread.run(Thread.java:825)

**Comment by gneissone** [comment]
A couple suggestions from the group during our dev call: 

- Try setting ABoxRecomputer to debug
- May have to add additional debug statements to ABoxRecomputer 

- Does it always fail on the same individual URI? If not, may be a concurrency issue somewhere. If yes, may be a data issue.
