### ISSUE TITLE
Docker containers usage: Server refused connection at: http://localhost:8983/solr/vivocore from VIVO container

### ISSUE THREAD

**Issue by MHector1** [vivo-project/VIVO#3786]
Not certain if this is an issue or my fault but I get this error using the VIVO Docker container. The Solr container is running fine and all of this is "OOTB", obtained here, no customization. (This is not related to another issue that somebody submitted here about a month ago where the SOLR container had to be renamed.) The error that I see browsing to localhost:8080 is:

FATAL: ApplicationImpl$ComponentsSetup
Could not set up the Solr search engine
edu.cornell.mannlib.vitro.webapp.application.ApplicationImpl$ComponentsSetup
org.apache.solr.client.solrj.SolrServerException: **Server refused connection at: http://localhost:8983/solr/vivocore**
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:650)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:255)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:244)

**Comment by jcabrerazuniga** [comment]
Try running:

docker ps -a 

and see if the solr container is running. After that, run docker inspect on the solr container to see if it is using server's port 8983 (I mean, the container's 8983 port should map to server's port 8983). I remember having a similar problem but the solr container had a different name to solr.

**Comment by GarrettArm** [comment]
possibly related to the situation where solr must finish initializing, and then the vivo container restarted.  

One workaround is to `docker compose up solr` -- wait 2 minutes -- `docker compose up`

**Comment by uebmaster** [comment]
Same for me in windows or ubuntu:

![Image](https://github.com/user-attachments/assets/a87326f7-3b22-4625-a9a3-d67f1ecef571)

**Comment by litvinovg** [comment]
@rischii please try using SOLR_URL=http://172.17.0.1:${SOLR_CONTAINER_PORT}/solr/vivocore
You might need to update it in vivo docker volume config/runtime.properties

**Comment by rischii** [comment]
@litvinovg 
thanks for the hint. It works now!

Adjusting the following line in runtime.properties:
`vitro.local.solr.url = http://localhost:8983/solr/vivocore`
to this worked for me:
`vitro.local.solr.url = http://vivo-solr:8983/solr/vivocore`

I would still flag this as a bug.
The line in runtime.properties should have been adjusted by the argument via the compose file:
`SOLR_URL=http://vivo-solr:${SOLR_CONTAINER_PORT}/solr/vivocore`
